### ISSUE TITLE
Question around dynamic env variables

### ISSUE THREAD

**Issue by jrmdayn** [inloop/cra-docker#2]
I would like to understand a bit more how I can read dynamic variables from window.ENV when I serve my app through your docker image. I don't quite get how the `env.js` file is injected / read by the app. Do I have to modify my index.html for it to work?

Sorry if this is obvious, but it was not clear to me from the README.

Thank you

**Comment by jakubknejzlik** [comment]
Hi @jeremie-stratumn, this is obvious, but unfortunately only to author :). I’ll update the README to mention it.

But to answer your question: there are multiple ways how to load the environment variable, but the easiest way is to add script tag to index.html file.

I’ll try to create some example app with the basic loading functionality.
